title: Universe Builders
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
logo: icon-with-text.png
url: https://universe.builders
search_enabled: true
favicon: favicon.ico

mermaid:
  version: "10.1.0"

footer_content: "Copyright &copy; 2023 Universe Builders PTY LTD. ACN: 667284504"

color_scheme: dark

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from