title: Universe Builders
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: "https://www.logolynx.com/images/logolynx/f6/f6e5b06f6aad7910506686b3c81137b8.png"
url: https://just-the-docs.github.io
search_enabled: true

mermaid:
  version: "9.1.3"

footer_content: "Copyright &copy; 2023 Universe Builders PTY LTD. ACN: 667284504"

#color_scheme: dark

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from